controller_manager:
  ros__parameters:
    update_rate: 30
    
    crobot_controller:
      type: crobot_controller/CrobotController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

crobot_controller:
  ros__parameters:
    front_left_wheel_name: "front_left_wheel_joint"
    back_left_wheel_name: "back_left_wheel_joint"
    front_right_wheel_name: "front_right_wheel_joint"
    back_right_wheel_name: "back_right_wheel_joint"
    open_loop: false
    position_feedback: true
    wheel_separation: 0.05
    wheel_separation_multiplier: 1.0
    wheel_radius: 0.05
    back_left_wheel_radius_multiplier: 1.0
    back_right_wheel_radius_multiplier: 1.0
    front_left_wheel_radius_multiplier: 1.0
    front_right_wheel_radius_multiplier: 1.0