#goal definition
geometry_msgs/PoseStamped[] points
---
#result definition

# Error codes
# Note: The expected priority order of the errors should match the message order
uint16 NONE=0
uint16 UNKNOWN=600
uint16 TASK_EXECUTOR_FAILED=601
uint16 NO_VALID_WAYPOINTS=602
uint16 STOP_ON_MISSED_WAYPOINT=603

# nav2_msgs/MissedWaypoint[] missed_waypoints
uint16 error_code
string error_msg
---
#feedback definition
float32 current_t_value