- ros_topic_name: "scan"
  gz_topic_name: "/world/empty/model/crobot/link/laser_frame/sensor/gpu_lidar/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition::msgs::LaserScan"
  direction: GZ_TO_ROS

# # gz topic published by Sensors plugin (Camera)
# - ros_topic_name: "camera/camera_info"
#   gz_topic_name: "camera/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "gz.msgs.CameraInfo"
#   direction: GZ_TO_ROS
